package com.quarx2k.cloudflare

import com.quarx2k.cloudflare.model.CloudFlareRegResponse
import java.io.File

class ConfigGenerator(private val privateKey: String, private val cloudFlareRegResponse: CloudFlareRegResponse) {

    public fun generate() : File {
        val config = File(String.format("wg0-cf-%s.conf", System.currentTimeMillis()))
        config.printWriter().use { out ->
            out.println("# Generated by https://github.com/Quarx2k/CloudFlareVpnConfigGenerator")
            out.println("[Interface]")
            out.println("PrivateKey = $privateKey")
            out.println("Address = ${cloudFlareRegResponse.config.localInterface.addresses.v4},${cloudFlareRegResponse.config.localInterface.addresses.v6}")
            out.println("DNS = 1.1.1.1")
            out.println()
            out.println("[Peer]")
            out.println("PublicKey = ${cloudFlareRegResponse.config.peers.first().public_key}")
            out.println("Endpoint  = ${cloudFlareRegResponse.config.peers.first().endpoint.host}")
            out.println("AllowedIPs = 0.0.0.0/0")
        }
        return config;
    }
}